### ISSUE TITLE
Can't connect to Loxone - unexpected end of JSON input

### ISSUE THREAD

**Issue by bsiebens** [XciD/loxone-prometheus-exporter#10]
Thanks for this amazing piece of software. It has been working up until a few days ago when I changed my password for Loxone. I changed the password also for the exporter but since then I keep getting the following error with no idea on what is going on or how to solve this.

> INFO[2022-05-20T08:39:16+02:00] Connecting to WS                             
> INFO[2022-05-20T08:39:16+02:00] Asking for Public Key                        
> INFO[2022-05-20T08:39:16+02:00] Starting websocket pump                      
> INFO[2022-05-20T08:39:16+02:00] Public Key OK                                
> INFO[2022-05-20T08:39:16+02:00] Key Exchange with Miniserver                 
> INFO[2022-05-20T08:39:16+02:00] Key Exchange OK                              
> INFO[2022-05-20T08:39:16+02:00] Authentication Starting                      
> ERRO[2022-05-20T08:39:16+02:00] unexpected end of JSON input

**Comment by XciD** [comment]
Does your password contain special char? Can you try changing it to the old one just to see if it works?

**Comment by bsiebens** [comment]
Only special character I use is a period, no other special characters. I'll try flipping it back to the old password and see what that does.

**Comment by bsiebens** [comment]
This has been laying around for quite a while, but yes flipping it back to the old password is making the exporter work fine again.
