### ISSUE TITLE
Flexible config handling

### ISSUE THREAD

**Issue by axxelG** [XciD/loxone-prometheus-exporter#5]
What do you think about a more flexible config management?

I don't like to provide credentials with command line parameters. I prefer using config files or environment variables.

I like to use https://github.com/spf13/viper but it only supports POSIX compatible flags so `-user` won't work anymore. You have to use `--user`.
There is a possible hack to keep it compatible. You can read the flags with the standard "flags" library and import them into "pflags" that viper uses. But I don't like this approach. Like every hack it might hurt in the future.

I created a PR: https://github.com/XciD/loxone-prometheus-exporter/pull/4

What are your thoughts?

**Comment by XciD** [comment]
Seems good for me :) I will adapt. 

I also use viper on other projet :)

**Comment by axxelG** [comment]
Was fixed with PR #4
